name: Deploy to Cloud Run

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Authenticate with Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Step 3: Set up gcloud CLI
      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: vijaya-23

      # Step 4: Configure Docker to use Artifact Registry
      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker us-docker.pkg.dev --quiet

      # Step 5: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t us-docker.pkg.dev/vijaya-23/cloudrun/master:latest .

      # Step 6: Push Docker image
      - name: Push Docker image
        run: |
          docker push us-docker.pkg.dev/vijaya-23/cloudrun/master:latest

      # Step 7: Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy application \
            --image us-docker.pkg.dev/vijaya-23/cloudrun/master:latest \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated \
            --project vijaya-23
