name: Deploy to Cloud Run

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: 'Auth Google Cloud SDK'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          
      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          project_id: vijaya-23
          export_default_credentials: true

      - name: 'Install gcloud beta'
        run: 'gcloud components install beta'

      - name: Authenticate Docker with gcloud
        run: |
          gcloud auth configure-docker us-docker.pkg.master --quiet
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

       - name: Configure Docker for Artifact Registry
         run: |
             gcloud auth configure-docker us-docker.pkg.dev


      - name: Build Docker image
        run: |
          docker build -t us-docker.pkg.dev/vijaya-23/cloudrun/master:latest .

      - name: Push Docker image
        run: |
          docker push us-docker.pkg.dev/vijaya-23/cloudrun/master:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy application \
            --image us-docker.pkg.dev/vijaya-23/cloudrun/master:latest \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated \
            --project vijaya-23
