name: Deploy to Cloud Run

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout source code
      - name: Checkout code
        uses: actions/checkout@v3

      # Authenticate with Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Set up Google Cloud SDK
      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ vijaya-23 }}

      # Configure Docker for Artifact Registry
      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker ${{ us-central1 }}-docker.pkg.dev --quiet

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ us-central1 }}-docker.pkg.dev/${{ vijaya-23 }}/cloudrun/app:latest .

      # Push Docker image to Artifact Registry
      - name: Push Docker image
        run: |
          docker push ${{ us-central1}}-docker.pkg.dev/${{ vijaya-23 }}/cloudrun/app:latest

      # Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy app \
            --image ${{ us-central1 }}-docker.pkg.dev/${{ vijaya-23 }}/cloudrun/app:latest \
            --region ${{us-central1 }} \
            --platform managed \
            --allow-unauthenticated \
            --project ${{vijaya-23 }}
